export const store = [
  {
    id: 1,
    category: "Hongo",
    name: "Hongo rosa",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
  {
    id: 2,
    category: "Hongo",
    name: "Hongo blanco",
    price: 400,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
  {
    id: 3,
    category: "Semilla",
    name: "Champi",
    price: 150,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
  {
    id: 4,
    category: "Sustrato",
    name: "Hongo  iluminati",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
  {
    id: 5,
    category: "Sustrato",
    name: "Hongo  iluminati",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
  {
    id: 6,
    category: "Sustrato",
    name: "MUSHJAR 500CC GRANO",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666845438/fungi/265-265x265_aiagh7.png",
  },
  {
    id: 7,
    category: "Sustrato",
    name: "MUSHJAR 500CC GRANO",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666845438/fungi/265-265x265_aiagh7.png",
  },
  {
    id: 8,
    category: "Sustrato",
    name: "MUSHJAR 500CC GRANO",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666845438/fungi/265-265x265_aiagh7.png",
  },
  {
    id: 9,
    category: "Sustrato",
    name: "MUSHJAR 500CC GRANO",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666845438/fungi/265-265x265_aiagh7.png",
  },
  {
    id: 10,
    category: "Sustrato",
    name: "MUSHJAR 500CC GRANO",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
  {
    id: 11,
    category: "Sustrato",
    name: "Hongo  iluminati",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
  {
    id: 12,
    category: "Hongo",
    name: "Hongo violeta",
    price: 200,
    incubacio: "21-27° C",
    induccion: "18-2°4 C.",
    desarrolloDeBasidiomas: "21-27° C",
    sustrato:
      "Coloniza con un micelio muy denso una gran variedad de sustratos tanto pasteurizados como esterilizados.",
    img: "https://res.cloudinary.com/dewegl2jr/image/upload/v1666701814/fungi/hongos/fotos/foto1_uwxgsl.jpg",
  },
];
